name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Test Backend and SonarCloud Analysis"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only proceed if the test-backend job was successful
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend Docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch

      # Build and push database Docker image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch

      # Build and push httpd Docker image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch
